spring:
  application:
    name: lcc-config-server  # 应用名称
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/lichencai/KW #配置文件所在仓库
          uri: https://gitee.com/lichencai/kv
          search-paths: test
          username: '793385991@qq.com'
          password: 'CvR7q@zA9Ukbmee'
          default-label: master
server:
  port: 6000