server:
  port: 6000

spring:
  application:
    name: lcc-config-server  # 应用名称
  cloud:
    bus:
      refresh:
        enabled: true
    config:
      server:
        git:
          uri: http://10.2.35.11/origin-5g-safe/config.git
          search-paths:
            - default
            - client*
          username: 'lichencai'
          password: 'lichencai12#$Test'
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: '*'
