server:
  port: 6000

spring:
  application:
    name: lcc-config-server  # 应用名称
  cloud:
    bus:
      refresh:
        enabled: true
    config:
      server:
        git:
          uri: https://gitee.com/lichencai/kv
          search-paths:
            - default
            - client*
          username: '793385991@qq.com'
          password: 'CvR7q@zA9Ukbmee'
          default-label: master
          basedir: cache
