server:
  port: 6000

spring:
  rabbitmq:
    host: 192.168.202.128
    port: 5672
    username: guest
    password: guest
  application:
    name: lcc-config-server  # 应用名称
  cloud:
    bus:
      refresh:
        enabled: true
    config:
      server:
        git:
          uri: https://gitee.com/lichencai/kv
          search-paths:
            - default
            - client*
          username: '793385991@qq.com'
          password: ''
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: '*'
