spring:
  application:
    name: lcc-config-server  # 应用名称
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lichencai/kv
          search-paths: test
          username: '793385991@qq.com'
          password: ''
          default-label: master
server:
  port: 6000