server:
  port: 6000
  servlet:
    context-path: /myenv

spring:
  application:
    name: lcc-config-server  # 应用名称
  cloud:
    bus:
      refresh:
        enabled: true
    config:
      server:
        prefix: /env
        git:
          uri: http://10.2.35.11/origin-5g-safe/config.git
          search-paths:
            - '*'
          username: 'lichencai'
          password: 'lichencai12#$Test'
          default-label: main
          basedir: cache
