server:
  port: 3302

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  rabbitmq:
    host: 192.168.202.128
    port: 5672
    username: guest
    password: guest
  profiles:
    active: uat # 名字以此作为环境区分
  application:
    name: client1   # 这里的命名需要和git上面的配置文件一样
  cloud:
    bus:
      refresh:
        enabled: true
  config:
    import: optional:configserver:http://localhost:6000